// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeOlokT2h7Wco9XA0B920cNzHGtz4DP7w',
    appId: '1:595875393228:web:8079f1cb75a793b8a39c69',
    messagingSenderId: '595875393228',
    projectId: 'sastraverse',
    authDomain: 'sastraverse.firebaseapp.com',
    storageBucket: 'sastraverse.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClIqt-fUF_lsd87fFYBa6r1h7_MCl7SeI',
    appId: '1:595875393228:android:aec01f890bb0ffe4a39c69',
    messagingSenderId: '595875393228',
    projectId: 'sastraverse',
    storageBucket: 'sastraverse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvcO5_6nTZDmlFnyonFL-2NFaTMohHdew',
    appId: '1:595875393228:ios:753724b2ee319b4ba39c69',
    messagingSenderId: '595875393228',
    projectId: 'sastraverse',
    storageBucket: 'sastraverse.firebasestorage.app',
    iosBundleId: 'com.example.sastraverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvcO5_6nTZDmlFnyonFL-2NFaTMohHdew',
    appId: '1:595875393228:ios:753724b2ee319b4ba39c69',
    messagingSenderId: '595875393228',
    projectId: 'sastraverse',
    storageBucket: 'sastraverse.firebasestorage.app',
    iosBundleId: 'com.example.sastraverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeOlokT2h7Wco9XA0B920cNzHGtz4DP7w',
    appId: '1:595875393228:web:7d2433c62cdd4244a39c69',
    messagingSenderId: '595875393228',
    projectId: 'sastraverse',
    authDomain: 'sastraverse.firebaseapp.com',
    storageBucket: 'sastraverse.firebasestorage.app',
  );
}
